urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.AnmeldeView.as_view(), name='anmeldung'),
    url(r'^([a-zA-Z0-9_-]{22})/$', views.ErstiView.as_view(), name='ersti'),
    url(r'^([a-zA-Z0-9_-]{22})/edit$', views.ErstiEditView.as_view(),
        name='ersti_edit'),
]

models.py
from django.db import models
from django.utils import timezone

import base64
import uuid

class Veranstaltung(models.Model):
    name = models.CharField(max_length = 50)
    anmeldung_beginn = models.DateTimeField()
    anmeldung_ende = models.DateTimeField()

    def __str__(self):
        return self.name

    def get_current():
        return Veranstaltung.objects.filter(anmeldung_beginn__lte=timezone.now(),
            anmeldung_ende__gte=timezone.now())[0]

class Studienfach(models.Model):
    ABSCHLUSS= (
        ('BA', 'Bachelor'),
        ('MA', 'Master'),
        ('Lv', 'Lehramt vertieft'),
        ('Ln', 'Lehramt nicht vertieft'),
    )
    FACHGRUPPE=(
        ('Ph', 'Physik'),
        ('In', 'Informatik'),
        ('Mi', 'Medieninformatik'),
        ('Ma', 'Mathematik'),
    )
    abschluss = models.CharField(max_length=2, choices=ABSCHLUSS)
    fachgruppe = models.CharField(max_length=2, choices=FACHGRUPPE)
    name = models.CharField(max_length=100)
    hauptfach = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Ersti(models.Model):
    ANREDE=(
        ('Hr', 'Herr'),
        ('Fr', 'Frau'),
        ('So', 'Sonstig'),
    )
    veranstaltung = models.ForeignKey(Veranstaltung)
    anrede = models.CharField(max_length=2, choices=ANREDE, default='So')
    vorname = models.CharField(max_length = 50)
    nachname = models.CharField(max_length = 50)
    studienfach = models.ForeignKey(Studienfach)
    infoverteiler = models.BooleanField(default = False)
    newsverteiler = models.BooleanField(default = False)
    datum = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.vorname + ' ' + self.nachname

class EMail(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4,
        editable=False)
    email = models.EmailField(null=True)
    verifiziert = models.BooleanField(default=False)
    ersti = models.ForeignKey(Ersti)

    def __str__(self):
        if self.email:
            return self.email
        else:
            return 'E-Mail entfernt'

    def get_link(self):
        return base64.urlsafe_b64encode(self.uid.bytes)[0:22].decode('utf-8')

    def from_link(link):
        return EMail.objects.get(uid=uuid.UUID(bytes=base64.urlsafe_b64decode(link+'==')))

class Kommentar(models.Model):
    ersti = models.ForeignKey(Ersti)
    text = models.TextField()
    datum = models.DateTimeField(auto_now_add=True)

templates/ophase_anmeldung/anmeldung.html
{% extends 'ophase_anmeldung/base.html' %}

{% load bootstrap3 %}

{% block title %}
  Anmeldung
{% endblock %}

{% block content %}

<p>Hallo lieber Faststudent,</p>

<p>wir wollen dir helfen einen guten Start in dein Studium zu finden. Die
Anmeldung dient uns zur Planung deiner Tutorgruppen und du erhälst immer
die aktuellsten Infos.</p>

<form action="{% url 'ophase_anmeldung:anmeldung' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='Absenden' reset='Löschen' %}{% endbuttons %}
</form>

{% endblock %}

templates/ophase_anmeldung/base.html
{% extends 'ophase_anmeldung/bootstrap.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
  <div class="container">
    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
  </div>
{% endblock %}

templates/ophase_anmeldung/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

templates/ophase_anmeldung/ersti.html
{% extends 'ophase_anmeldung/base.html' %}

{% load bootstrap3 %}

{% block title %}
{{ object.veranstaltung.name }}
{% endblock %}

{% block content %}

<p>Hallo {{ object.vorname }} {{ object.nachname }},</p>

<p>vielen Dank für deine Anmeldung zur {{ object.veranstaltung.name }}.
Bitte überprüfe ob deine Daten korrekt sind, wir werden dir rechtzeitig
vor der Veranstaltung eine Mail mit allen nötigen Informationen zukommen
lassen.</p>

<p>Folgende Daten sind bei uns hinterlegt <a href="edit">(bearbeiten)</a></p>

<table class="table table-striped">
<tr>
  <th>Name</th>
  <td>{{ object.anrede }} {{ object.vorname }} {{ object.nachname }}</td>
</tr>
<tr>
  <th>E-Mailadresse</th>
  <td>{% for mail in object.email_set.all %}{{mail.email}}{% endfor %}</td>
</tr>
<tr>
  <th>Studienfach</th>
  <td>{{ object.studienfach.name }}
</tr>
<tr>
  <th>Verteiler</th>
  <td>Info:
    {% if objects.infoverteiler %}
      {% bootstrap_icon "ok" %}
    {% else %}
      {% bootstrap_icon "cancel" %}
    {% endif %}
    News:
    {% if objects.newsverteiler %}
      {% bootstrap_icon "ok" %}
    {% else %}
      {% bootstrap_icon "cancel" %}
    {% endif %}
  </td>
</tr>
<tr>
</table>

<h2>Kommentare</h2>
<table class="table table-striped"/>
{% for kommentar in object.kommentar_set.all %}
  <tr>
    <td>{{ kommentar.text }}</td>
  </tr>
{% endfor %}
</table>
<form action="{% url 'ophase_anmeldung:ersti' uid %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='Kommentar hinzufügen' %}{% endbuttons %}
</form>

{% endblock %}

templates/ophase_anmeldung/ersti_edit.html
{% extends 'ophase_anmeldung/base.html' %}

{% load bootstrap3 %}

{% block title %}
  Daten ändern
{% endblock %}

{% block content %}

<form action="{% url 'ophase_anmeldung:ersti_edit' uid %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='Aktualisieren' %}{% endbuttons %}
</form>

{% endblock %}